apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-challenge-app
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-challenge-app
  template:
    metadata:
      labels:
        app: devops-challenge-app
    spec:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
