apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-challenge-app
  name: pyhton-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-challenge-app
  template:
    metadata:
      labels:
        app: devops-challenge-app
    spec:
      - name: python_app
        image: mohamedmamdouhiv/projects-images:v1.0
        ports:
         - containerPort: 8000